### ISSUE TITLE
Replace Random by ThreadLocalRandom

### ISSUE THREAD

**Issue by hugmanrique** [canyonmodded/canyon#1]
https://github.com/canyonmodded/Canyon-Server/blob/75138b4e0bd5c8e8a7baecc3b222950da09b0709/CraftBukkit-Patches/0011-Shared-random-for-all-entities.patch#L15

Since entity ticking is always performed on the main thread, we can replace the `Random` by a `ThreadLocalRandom` to remove the unneeded synchronization, thus improving performance.

**Comment by astei** [comment]
This is not always guaranteed. We need the `Random` instance as soon as the first tick, and the `Entity` constructor is a natural place to do it. In addition, a dumb switch to `ThreadLocalRandom` would introduce concurrency issues when we eventually add async chunk loading.

In any event, the seed value in `Entity` shouldn't be contended anyway, so there's only a very minor efficiency gain to be had by moving to `ThreadLocalRandom`.
