### ISSUE TITLE
CanyonBukkitTask.cancel() is not thread-safe

### ISSUE THREAD

**Issue by hugmanrique** [canyonmodded/canyon#2]
https://github.com/canyonmodded/Canyon-Server/blob/75138b4e0bd5c8e8a7baecc3b222950da09b0709/CraftBukkit-Patches/0010-Bukkit-scheduler-rewrite.patch#L67

I don't know whether the original implementation was thread-safe or not, but I've seen some plugins cancel async task from their own `run()` method. Making `isCancelled volatile` will fix this problem.

**Comment by astei** [comment]
Closed as the scheduler patch is now dropped.
