### ISSUE TITLE
Error on Server Start

### ISSUE THREAD

**Issue by ghost** [canyonmodded/canyon#25]
https://hastebin.com/ucirijacez.coffeescript

**Comment by astei** [comment]
You built Canyon on a version of Java 9 or higher but ran it on Java 8 or lower. The fix is to build on Java 8.

**Comment by ghost** [comment]
If you have some advice on how to do that that'd be great

**Comment by astei** [comment]
Make sure that when you run Maven, it uses Java 8. See how you can change your default Java version.

**Comment by astei** [comment]
Alternatively, run Canyon on Java 11.
