### ISSUE TITLE
Error installing canyon git on my server.

### ISSUE THREAD

**Issue by bmlrX3k** [canyonmodded/canyon#26]
Hi, I found out about your project recently and it's great!
However, I had a problem, but don't worry, I solved it. I'm writing this message to let you know about it:
After retrieving all the files via git, no problem. I run the command "sudo ./canyon p", no problem here too. But I had to install a software to be able to run the command "sudo mvn clean package". And this is where I had a problem, everything works except at the moment (if I understood correctly) when I downloaded the server I think, it had an error. After reading the error, I executed this command :
"sudo mvn clean package -X" and the problem was solved. I had I think a problem during the downloading phase I think. My server is currently hosted at OVH in Germany, so I doubt that the throughput is bad. Well, this was to share my current concerns, if I have any more I'll let you know.
With kind regards.

**Comment by astei** [comment]
Do you have any specific errors? It could've been a transient issue.

**Comment by bmlrX3k** [comment]
I'm sorry but I don't have the previous logs anymore, I just remember that the download had failed ...
