### ISSUE TITLE
tps command stops working on server reload

### ISSUE THREAD

**Issue by ghost** [canyonmodded/canyon#29]
1. Start the server.
2. Observe that the /tps command is working.
3. Type "reload" into the server console.
4. "Unknown command. Type "help" for help." message appears when running /tps again. Any command aliases that point to /tps in bukkit.yml will fail to bind.

**Comment by js6pak** [comment]
`CraftServer.java:105` TpsCommand is only registered on start
![image](https://user-images.githubusercontent.com/35262707/76171830-d92c5400-618f-11ea-8fc3-23d447d2c4dc.png)
Fix could be moving command registration from `CraftServer` to `SimpleCommandMap#setDefaultCommands`

**Comment by astei** [comment]
My opinion is that [/reload is unsafe](https://matthewmiller.dev/blog/problem-with-reload/). It is unviable on newer versions of Minecraft and still caused significant issues even in 2011.

I consider this a bug and I will fix it.
