### ISSUE TITLE
Text kicking players

### ISSUE THREAD

**Issue by ghost** [canyonmodded/canyon#30]
When the following lines are typed, players are kicked from the game every single time.
`So many roaming creepers still`

Once typing `:o` kicked me.

Various lines of text are kicking us left and right.

**Comment by astei** [comment]
Paste your `canyon.yml` and also any relevant logs you may have.

**Comment by ghost** [comment]
Canyon.yml:
https://hastebin.com/limepaniga.sql

Conversation:
https://hastebin.com/rebixizame.xml

**Comment by astei** [comment]
Please set `settings.use-new-networking-stack` in `canyon.yml` to `false` and try again

**Comment by ghost** [comment]
In my testing I couldn't get it to kick when setting:
`settings.use-new-networking-stack: false`

**Comment by ghost** [comment]
The kick happens with any message that's exactly 30 characters when using the new networking stack.

**Comment by astei** [comment]
Thanks, will investigate further. Won't be surprised if it's something stupid.

**Comment by astei** [comment]
I was able to reproduce the issue.

**Comment by astei** [comment]
I did some further experimentation. The fix is to teach Canyon the "correct" size of all incoming packets, so that they can be framed correctly.

**Comment by astei** [comment]
Fixed. The problem was `Packet10Flying` not correctly dealing with EOFs.
