### ISSUE TITLE
Mob Spawn By Bed

### ISSUE THREAD

**Issue by ghost** [canyonmodded/canyon#31]
Sleeping in a bed which is touching an exterior wall to a house will cause mobs to spawn by the side of the bed within the house.

Discussion thread related to this issue: https://www.minecraftforum.net/forums/minecraft-java-edition/survival-mode/239551-mobs-suddenly-spawning-next-to-my-bed-as-i-fall

(Edit: Unsure totally if this is a bug, but given that they spawn only if this strange condition is met, it leads me to believe that it is.)

Edit 2: Bed template: https://minecraft.gamepedia.com/File:Bed_Template.png

**Comment by js6pak** [comment]
But isn't it beta feature?

**Comment by astei** [comment]
This is a vanilla feature. Closing this issue.
