### ISSUE TITLE
Block-break bugs

### ISSUE THREAD

**Issue by ghost** [canyonmodded/canyon#33]
Block breaking bugs I've encountered:
- Crafting tables do not break faster using an axe
- Redstone ore does not break quickly enough using a pickaxe
- Wood slabs are mined fast with pickaxe, and **not an axe**
- (Will add more if found)

**Comment by ghost** [comment]
You need to patch both the client and server to properly fix this, otherwise blocks will disappear before the breaking animation completes on the client-side.

**Comment by ghost** [comment]
Oh I didn't realize that. I'd be interested in a client mod to accompany a server fix, but that would be more in depth than what's currently being offered.

I also have a lot of block-interact bugs and block-place bugs I can post if needed.

**Comment by js6pak** [comment]
This is again vanilla "feature" and not canyon bug

**Comment by ghost** [comment]
Using a pickaxe on wood to break it faster than an axe is… a bug.

A feature isn’t a beta inconsistency that contradicts how to play the game, but sure, it is part of the beta. I am trying to help report bugs, so the beta is more playable. I think that is the intention of canyon.

(In my other issue if I am wrong and it’s a feature then great, I don’t want it changed either. I noted I was not sure.)

**Comment by astei** [comment]
If the behavior is identical on the client and server, Canyon can't fix it without also providing a client mod to adequately fix it on the client. I'm not really inclined to fix issues with block breaking speed for this reason.

However, other gameplay issues are within purview of Canyon. But if the issue requires a client mod to fix, there's little recourse. (Fixed online-mode support is an exception.)
