### ISSUE TITLE
Port hopper optimization patch from Paper

### ISSUE THREAD

**Issue by nadecancode** [canyonmodded/canyon#42]
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0414-Optimize-Hoppers.patch

I tried to port this by myself, but sorry, due to my ability I could not accomplish this.

**Comment by astei** [comment]
I think I know why you were having so much trouble: you’re looking at a project that targets a version of Minecraft that doesn’t have hoppers!

This project is for Beta Minecraft, not for release version 1.7.x.
